backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"   # waar files in de repo komen
public_folder: "/images/uploads"        # hoe ze publiek heten

publish_mode: editorial_workflow        # concept -> review -> public (optioneel)
locale: "nl"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Titel",        name: "title",       widget: "string" }
      - { label: "Omschrijving", name: "description", widget: "text", hint: "max ~160" }
      - { label: "Datum",        name: "date",        widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Cover",        name: "cover",       widget: "image", required: false }
      - { label: "Tags",         name: "tags",        widget: "list", required: false }
      - { label: "Concept",      name: "draft",       widget: "boolean", default: false }
      - { label: "Inhoud",       name: "body",        widget: "markdown" }
