backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"   # waar bestanden in je repo komen
public_folder: "/images/uploads"        # publieke URL op de site

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Titel",        name: "title",       widget: "string" }
      - { label: "Omschrijving", name: "description", widget: "text" }
      - { label: "Datum",        name: "date",        widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Concept",      name: "draft",       widget: "boolean", default: false }
      - { label: "Inhoud",       name: "body",        widget: "markdown" }
